# Generated by Django 4.2.4 on 2023-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256, null=True)),
                ('artwork', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('loi', models.TextField(null=True)),
            ],
        ),
    ]
