# Generated by Django 4.2.4 on 2023-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlatform', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='music',
        ),
        migrations.AddField(
            model_name='review',
            name='music_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
