# Generated by Django 4.2.4 on 2023-08-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlatform', '0003_remove_review_music_review_music_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='music_id',
        ),
        migrations.AddField(
            model_name='review',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicPlatform.music'),
        ),
    ]
