# Generated by Django 4.2.4 on 2023-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('musicPlatform', '0006_music_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artwork',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='images/review'),
        ),
    ]
