# Generated by Django 4.2.4 on 2023-08-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicPlatform.music')),
            ],
        ),
    ]
