# Generated by Django 4.2.4 on 2023-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlatform', '0008_music_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.FileField(max_length=256, null=True, upload_to=''),
        ),
    ]
