# Generated by Django 4.2.4 on 2023-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlatform', '0009_alter_music_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
